name: server
description: lightweight trello analog - server
version: 1.0.0
author: yury.kornienko geo97it@gmail.com

environment:
  sdk: ^2.2.0

dependencies:
  ansicolor: ^1.0.2
  aqueduct: ^3.2.0
  api_models:
    path: ../api_models

dev_dependencies:
  pedantic: ^1.5.0
